### ISSUE TITLE
Link from the cddlib homepage to the github repository

### ISSUE THREAD

**Issue by saraedum** [cddlib/cddlib#18]
@timokau who packages cddlib for NiX suggested on SageMath's issue tracker:
> Thanks for your work, that greatly simplifies packaging :) Every patch replaced by something upstream supported is a win.
> 
> Could you maybe ask them to make a note on the cddlib homepage? That would help people that stumble there and also make it seem a bit more legit.

@komeifukuda, could you update the cdd homepage to mention this page on github? Or does it already and we missed the link somehow?

**Comment by komeifukuda** [comment]
Sure, I will update the cddlib homepage and add the link to GitHub very soon.

**Comment by timokau** [comment]
This is done now: https://www.inf.ethz.ch/personal/fukudak/cdd_home/index.html

Thanks @komeifukuda!
