### ISSUE TITLE
Building from source requires latex

### ISSUE THREAD

**Issue by timokau** [cddlib/cddlib#19]
While updating the nix package I noticed that building from source now requires latex. However the error message wasn't very intuitive:

```
Making all in doc
  make[1]: Entering directory '/tmp/nix-build-cddlib-0.94j.drv-0/source/doc'
  make[1]: *** No rule to make target 'cddlibman.pdf', needed by 'all-am'.  Stop.
```

And the dependency is not mentioned in the README's building from source section.

**Comment by timokau** [comment]
Github is becoming really unreliable lately, missing email notifications all the time :/

No, I build from a clone of the git repo at the release tag. I prefer to build the binary artefacts myself.

**Comment by saraedum** [comment]
@timokau please have a look at #20. Would that have been sufficient in your case?

**Comment by timokau** [comment]
Yes, that looks good to me. Thanks for taking the initiative to improve the cddlib build :)
