### ISSUE TITLE
Consider installing headers in ${prefix}/include/cdd/ instead of ${prefix}/include

### ISSUE THREAD

**Issue by mkoeppe** [cddlib/cddlib#26]
Ubuntu does that, probably to make `/usr/include` tidier and reduce the potential for clashes (note `setoper.h` has a very generic name).
So software using cddlib already has to check for this directory anyway.

**Comment by mkoeppe** [comment]
Decision?

**Comment by saraedum** [comment]
Sure. Would you mind creating a PR? (#27 puts headers into cddlib/ which is the not the right thing to do given the legacy imho.)

**Comment by mkoeppe** [comment]
OK I will prepare a pull request

**Comment by saraedum** [comment]
Thanks!
