### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by JoergRambau** [cddlib/cddlib#43]
Dear team,

I am Jörg Rambau (the author of TOPCOM), and I have been using the cddlib exact rational LP solver for a long time for checking regularity of triangulations of point configurations. 

I came accross the following problem: When running multiple instances of cdd in parallel threads, the program crashes in random places, indicating that threads access the heap concurrently in cddlib. I could clarify that this is due to a small number of static variables inside cdd functions.

As a test, I patched this release to use "thread_local" for all these (and the real global) variables and compiled as c++11 code.  That works perfectly. Still, compiling cddlib as c++ code is only a hack, in my view.

My knowledge of thread-local storage (TLS) in modern C11 and compiler support is limited. Thus, I do not know whether the same could be achieved in C11. In my experience, builtin types can be made TLS in C, while structures cannot.  But maybe I am mistaken.

For me it would be very useful if this (small?) change of all statics and globals to TSL could be incorporated into an official release so that I do not have to use the c++ detour in TOPCOM.

Thanks a lot!

Best, 
          Jörg

**Comment by saraedum** [comment]
Sorry that no one replied earlier. I certainly won't have time to work on this but feel free to propose something in a PR.

The proper way of fixing this would be not to use static variables at all but that's probably a lot of work.

I am not sure whether thread static is really the correct solution. The result is that you cannot move a computation between threads even if the actual computation runs never on more than one thread. That seems to be fine in your application but I am not sure that that will make everybody happy.

**Comment by JoergRambau** [comment]
Dear Julian,

Thanks for your reply.

Thread local & C++-compiler is kind of the minimal-invasive work-around that
avoids heavy locking.  Unfortunately, I cannot do more than this.

So long, Jörg

**Comment by dimpase** [comment]
@JoergRambau - please provide us your patches.

**Comment by dimpase** [comment]
@JoergRambau - I keep getting bounces from your apparent attempts to email me files which our over-eager spam filters consider harmful. Could you attach them here instead?

**Comment by dimpase** [comment]
This is fixed in https://github.com/cddlib/cddlib/commit/1210faf9ee9cf02e29fc67e11a8ea4e847c58ddd

**Comment by saraedum** [comment]
@dimpase thanks for improving upon that.

Could you add something in `news/` also?

I think it's best to make changes through Pull Requests in the future so people get a chance to comment on the proposed changes.

**Comment by dimpase** [comment]
Sure, I'll do that. 

Sorry for not going through a PR - I've hit `git push` a bit too soon...

**Comment by dimpase** [comment]
@saraedum - I'm confused about `news/` - it contains a template, but how is it supposed to be used?

**Comment by dimpase** [comment]
I can of course add stuff directly to ChangeLog

**Comment by saraedum** [comment]
see https://github.com/cddlib/cddlib/blob/master/.github/pull_request_template.md
