### ISSUE TITLE
Release 0.94m

### ISSUE THREAD

**Issue by saraedum** [cddlib/cddlib#58]
As pointed out by @komeifukuda in private mail, we should cut a new release.

Anything else you would like to happen for 0.94m? If not, I'll go ahead and release 0.94m in a few days.

**Comment by komeif** [comment]
@saraedum Thank you very much for your initiative.  One more thing I already mentioned earlier is to update dd_DDVERSION in cddtypes.h.  Currently in cddlib-0.94l, we have a wrong number.
#define dd_DDVERSION   "Version 0.94j"
This version appears in output of many programs, and so this should be correct to know what version is running.  We can also put the date like "Version 0.94m (December 1, 2020)".
