### ISSUE TITLE
dd_ExistsRestrictedFace: R and S ever set to non-zero?

### ISSUE THREAD

**Issue by Zeta611** [cddlib/cddlib#62]
I've been following the source and read cddlibman, and encountered the function: `dd ExistsRestrictedFace`.
However, checking all the use cases of the function, I can't seem to find where the arguments `R` and `S` are ever set after being initialized.
Am I missing something, or is this implemented for a customized use case which is not shown in the examples & main logic?

**Comment by saraedum** [comment]
@komeifukuda you probably know best what is supposed to happen in this function. Could you comment?

**Comment by komeif** [comment]
I do not understand the question.  The user has to set the sets R and S as he/she wishes and calls the function.
For example, see allfaces.c code in src directory to enumerate all faces of a polyhedron.

**Comment by Zeta611** [comment]
@komeif Thank you for the comment!

In `allfaces.c` I can see that both are initialized by
```c
set_initialize(&R, M->rowsize); 
set_initialize(&S, M->rowsize); 
```
but can't find where they are set by the user.

So, should I set these programmatically using `set_addelem`?

**Comment by komeif** [comment]
@Zeta611  You have to look at what the function call FaceEnum(M, R, S, rip, mindim) does.
The main calls this recursive function with both R, S empty.  The function recognizes
the facets of the original polyhedron and then sets R, S accordingly, as you see
the FaceEnum function where various set functions set_* are used.
