### ISSUE TITLE
problem installing cddlib in a remote cluster

### ISSUE THREAD

**Issue by tiagomartinelli93** [cddlib/cddlib#68]
Hi,

I'm getting the following error when trying to install via pip install -U pycddlib in a jupyter notebook:

Defaulting to user installation because normal site-packages is not writeable
Collecting pycddlib
  Using cached pycddlib-2.1.6.tar.gz (159 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycddlib
  Building wheel for pycddlib (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Compiling cdd.pyx because it changed.
      [1/1] Cythonizing cdd.pyx
      building 'cdd' extension
      creating build
      creating build/temp.linux-x86_64-3.7
      creating build/temp.linux-x86_64-3.7/cddlib
      creating build/temp.linux-x86_64-3.7/cddlib/lib-src
      gcc -pthread -B /opt/tljh/user/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DGMPRATIONAL -Icddlib/lib-src -I/opt/tljh/user/include/python3.7m -c cdd.c -o build/temp.linux-x86_64-3.7/cdd.o
      In file included from cddlib/lib-src/cdd.h:17,
                       from cdd.c:988:
      cddlib/lib-src/cddmp.h:30:11: fatal error: gmp.h: No such file or directory
         30 |  #include "gmp.h"
            |           ^~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycddlib
  Running setup.py clean for pycddlib
Failed to build pycddlib
Installing collected packages: pycddlib
  Running setup.py install for pycddlib ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pycddlib did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running install
      running build
      running build_ext
      Compiling cdd.pyx because it depends on cddlib_f.pxi.
      [1/1] Cythonizing cdd.pyx
      building 'cdd' extension
      creating build
      creating build/temp.linux-x86_64-3.7
      creating build/temp.linux-x86_64-3.7/cddlib
      creating build/temp.linux-x86_64-3.7/cddlib/lib-src
      gcc -pthread -B /opt/tljh/user/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DGMPRATIONAL -Icddlib/lib-src -I/opt/tljh/user/include/python3.7m -c cdd.c -o build/temp.linux-x86_64-3.7/cdd.o
      In file included from cddlib/lib-src/cdd.h:17,
                       from cdd.c:988:
      cddlib/lib-src/cddmp.h:30:11: fatal error: gmp.h: No such file or directory
         30 |  #include "gmp.h"
            |           ^~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycddlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Note: you may need to restart the kernel to use updated packages.

**Comment by saraedum** [comment]
The system seems to be lacking GMP headers.

This is a problem in pycddlib's setup. I believe you should report this at https://github.com/mcmtroffaes/pycddlib/.
